In [1]:
from __future__ import division, print_function
import numpy as np

In [2]:
point ={'match': 2, 'mismatch': -1, 'gap': -1}

In [3]:
def matching1(alpha, beta):
    if alpha == beta:
        return point['match']
    elif alpha == '-' or beta == '-':
        return point['gap']
    else:
        return point['mismatch']
    

In [4]:
def water(s1, s2):
    m, n = len(s1), len(s2)
    V = np.zeros((m+1, n+1))    
    T = np.zeros((m+1, n+1))
    max_score = 0
    
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            sc_diag = V[i-1][j-1] + matching1(s1[i-1], s2[j-1])
            sc_up = V[i][j-1] + point['gap']
            sc_left = V[i-1][j] + point['gap']
            V[i][j] = max(0,sc_left, sc_up, sc_diag)
            if V[i][j] == 0: T[i][j] = 0
            if V[i][j] == sc_left: T[i][j] = 1
            if V[i][j] == sc_up: T[i][j] = 2
            if V[i][j] == sc_diag: T[i][j] = 3
            if V[i][j] >= max_score:
                max_i = i
                max_j = j
                max_score = V[i][j];
    
    
    print('V=\n',V,'\n')
    print('T=\n',T,'\n')
    align1, align2 = '', ''
    i,j = max_i,max_j
    
    
    while T[i][j] != 0:
        if T[i][j] == 3:
            a1 = s1[i-1]
            a2 = s2[j-1]
            i -= 1
            j -= 1
        elif T[i][j] == 2:
            a1 = '-'
            a2 = s2[j-1]
            j -= 1
        elif T[i][j] == 1:
            a1 = s1[i-1]
            a2 = '-'
            i -= 1
        print(a1,a2)
        align1 += a1
        align2 += a2
        
        

    align1 = align1[::-1]
    align2 = align2[::-1]
    sym = ''
    iden = 0
    
    
    for i in range(len(align1)):
        a1 = align1[i]
        a2 = align2[i]
        if a1 == a2:                
            sym += a1
            iden += 1
        elif a1 != a2 and a1 != '-' and a2 != '-': 
            sym += ' '
        elif a1 == '-' or a2 == '-':          
            sym += ' '
            
            
    
    identity = iden / len(align1) * 100
    print('Identity = %f percent' % identity)
    print('Score =', max_score)
    print(align1)
    print(sym)
    print(align2)

In [5]:
water('AGCACACA','ACACACTA')

V=
 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  1.  2.  1.  2.  1.  0.  2.]
 [ 0.  1.  1.  1.  1.  1.  1.  0.  1.]
 [ 0.  0.  3.  2.  3.  2.  3.  2.  1.]
 [ 0.  2.  2.  5.  4.  5.  4.  3.  4.]
 [ 0.  1.  4.  4.  7.  6.  7.  6.  5.]
 [ 0.  2.  3.  6.  6.  9.  8.  7.  8.]
 [ 0.  1.  4.  5.  8.  8. 11. 10.  9.]
 [ 0.  2.  3.  6.  7. 10. 10. 10. 12.]] 

T=
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 2. 3. 2. 3. 2. 2. 3.]
 [0. 1. 3. 1. 3. 1. 3. 3. 1.]
 [0. 1. 3. 2. 3. 2. 3. 2. 2.]
 [0. 3. 1. 3. 2. 3. 2. 2. 3.]
 [0. 1. 3. 1. 3. 2. 3. 2. 2.]
 [0. 3. 1. 3. 1. 3. 2. 2. 3.]
 [0. 1. 3. 1. 3. 1. 3. 2. 2.]
 [0. 3. 1. 3. 1. 3. 1. 3. 3.]] 

A A
- T
C C
A A
C C
A A
C C
G -
A A
Identity = 77.777778 percent
Score = 12.0
AGCACAC-A
A CACAC A
A-CACACTA
